--Mức 1:
SELECT NV.*
FROM BENHVIEN BV, BANGCAP BC, NHANVIEN_BANGCAP NVBC, NHANVIEN NV
WHERE BV.MABV = NV.MABV
AND NV.MANV = NVBC.MANV
AND NVBC.MABC = BC.MABC
AND NV.GIOITINH = 'Nam'
AND YEAR(NGSINH) > 1980
AND BC.TENBANGCAP = 'ckrhm'
AND BV.TENBV = 'Binh Duong'

--Mức 2:
SELECT NV.*
FROM BANGCAP BC, NHANVIEN_BANGCAP2 NVBC, NHANVIEN2 NV
WHERE NV.MANV = NVBC.MANV
AND NVBC.MABC = BC.MABC
AND NV.GIOITINH = 'Nam'
AND YEAR(NGSINH) > 1980
AND BC.TENBANGCAP = 'ckrhm'