-- 1. T?o User
CREATE USER BAITHI IDENTIFIED BY baithi;
ALTER USER BAITHI quota 100M ON USERS;

CREATE TABLE BAITHI.TUYEN
(
    MATUYEN CHAR(4) CONSTRAINT PK_TU PRIMARY KEY,
    BENDAU VARCHAR2(20),
    BENCUOI VARCHAR2(20),
    GIATUYEN NUMBER(7),
    NGXB DATE,
    TGDK NUMBER(3)
);

CREATE TABLE BAITHI.XE
(
    MAXE CHAR(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(30),
    MATUYEN CHAR(4),
    SOGHET1 NUMBER(3),
    SOGHET2 NUMBER(3),
    CONSTRAINT FK_XE_TU FOREIGN KEY(MATUYEN) REFERENCES BAITHI.TUYEN(MATUYEN)
);

CREATE TABLE BAITHI.KHACH
(
    MAKH CHAR(4) CONSTRAINT PK_KH PRIMARY KEY,
    HOTEN VARCHAR(40),
    GIOITINH VARCHAR(3),
    CMND VARCHAR(20)
);

CREATE TABLE BAITHI.VEXE
(
    MATUYEN CHAR(4),
    MAHK CHAR(4),
    NGMUA DATE,
    GIAVE NUMBER(7),
    CONSTRAINT FK_VE_TU FOREIGN KEY(MATUYEN) REFERENCES BAITHI.TUYEN(MATUYEN),
    CONSTRAINT FK_VE_KH FOREIGN KEY(MAHK) REFERENCES BAITHI.KHACH(MAKH),
    CONSTRAINT PK_VX PRIMARY KEY(MATUYEN, MAHK)
); 

SELECT * FROM BAITHI.TUYEN;
--- 2. Nh?p d? li?u m?u
INSERT INTO BAITHI.TUYEN VALUES('T11A', 'SG', 'DL', 210000, TO_DATE('26/12/2016','dd/MM/yyyy'), 6);
INSERT INTO BAITHI.TUYEN VALUES('T32D', 'PT', 'SG', 120000, TO_DATE('30/12/2016','dd/MM/yyyy'), 4);
INSERT INTO BAITHI.TUYEN VALUES('T06F', 'NT', 'DNG', 225000, TO_DATE('02/01/2017','dd/MM/yyyy'), 7);

INSERT INTO BAITHI.XE VALUES('X01', '52LD-4393', 'T11A', 20, 20);
INSERT INTO BAITHI.XE VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BAITHI.XE VALUES('X03', '55LD-6850', 'T06F', 15, 15);

INSERT INTO BAITHI.KHACH VALUES('KH01', 'Lam Van Ben','Nam', '655615896');
INSERT INTO BAITHI.KHACH VALUES('KH02', 'Duong Thi Luc','Nu', '275648642');
INSERT INTO BAITHI.KHACH VALUES('KH03', 'Hoang Thanh Tung','Nam', '456889143');

INSERT INTO BAITHI.VEXE VALUES('T11A', 'KH01', TO_DATE('20/12/2016','dd/MM/yyyy'), 210000);
INSERT INTO BAITHI.VEXE VALUES('T32D', 'KH02', TO_DATE('25/12/2016','dd/MM/yyyy'), 144000);
INSERT INTO BAITHI.VEXE VALUES('T06F', 'KH03', TO_DATE('30/12/2016','dd/MM/yyyy'), 270000);

--3. Hi?n th?c ràng bu?c toàn v?n sau: Các tuy?n xe có Th?i gian d? ki?n l?n h?n 5 ti?ng luôn có 
--giá tuy?n l?n h?n 200.000.
--4. Hi?n th?c ràng bu?c toàn v?n sau: Tuy?n xe có ngày xu?t b?n t? ngày 29/12/2016 ??n ngày 
--05/01/2017 s? có giá vé t?ng 20%.

--5. Tìm t?t c? các vé xe mua trong tháng 12, s?p x?p k?t qu? gi?m d?n theo giá vé.
SELECT *
FROM BAITHI.VEXE
WHERE EXTRACT(MONTH FROM NGMUA) = 12
ORDER BY GIAVE DESC;

--6. Tìm tuy?n xe có s? vé xe ít nh?t trong n?m 2016.
SELECT T.MATUYEN, COUNT(*)
FROM BAITHI.TUYEN T, BAITHI.VEXE V
WHERE T.MATUYEN = V.MATUYEN AND EXTRACT(YEAR FROM NGMUA) = 2016
GROUP BY T.MATUYEN 
HAVING COUNT(*) <= ALL( SELECT COUNT(*)
                        FROM BAITHI.TUYEN T, BAITHI.VEXE V 
                        WHERE T.MATUYEN = V.MATUYEN AND EXTRACT(YEAR FROM NGMUA) = 2016
                        GROUP BY T.MATUYEN);
                        
--7. Tìm tuy?n xe có c? hành khách nam và hành khách n? mua vé.
SELECT MATUYEN
FROM BAITHI.VEXE V , BAITHI.KHACH K 
WHERE K.MAKH = V.MAHK AND GIOITINH ='Nam'
INTERSECT
SELECT MATUYEN
FROM BAITHI.VEXE V, BAITHI.KHACH K 
WHERE K.MAKH = V.MAHK AND GIOITINH ='Nu';

--8. Tìm hành khách n? ?ã t?ng mua vé t?t c? các tuy?n xe
SELECT MAKH
FROM BAITHI.KHACH K
WHERE GIOITINH = 'Nu'
AND NOT EXISTS(   SELECT *
                    FROM BAITHI.TUYEN T
                    WHERE NOT EXISTS(   SELECT *
                                        FROM    BAITHI.VEXE V
                                        WHERE   V.MATUYEN = T.MATUYEN
                                                AND V.MAHK = K.MAKH )); 