-- 1. TẠO USER
DROP USER BAITHI CASCADE;
CREATE USER BAITHI IDENTIFIED BY baithi;

ALTER USER BAITHI QUOTA 100M ON USERS;

CREATE TABLE BAITHI.TUYEN (
    MATUYEN CHAR(4) CONSTRAINT PK_TU PRIMARY KEY,
    BENDAU VARCHAR2(20),
    BENCUOI VARCHAR2(20),
    GIATUYEN NUMBER(7),
    NGXB DATE,
    TGDK NUMBER(3)
);

CREATE TABLE BAITHI.XE (
    MAXE CHAR(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(30),
    MATUYEN CHAR(4),
    SOGHET1 NUMBER(3),
    SOGHET2 NUMBER(3),
    CONSTRAINT FK_XE_TU FOREIGN KEY(MATUYEN) REFERENCES BAITHI.TUYEN(MATUYEN)
);

CREATE TABLE BAITHI.KHACH (
    MAKH CHAR(4) CONSTRAINT PK_KH PRIMARY KEY,
    HOTEN VARCHAR(40),
    GIOITINH VARCHAR(3),
    CMND VARCHAR(20)
);

CREATE TABLE BAITHI.VEXE (
    MATUYEN CHAR(4),
    MAHK CHAR(4),
    NGMUA DATE,
    GIAVE NUMBER(7),
    CONSTRAINT FK_VE_TU FOREIGN KEY(MATUYEN) REFERENCES BAITHI.TUYEN(MATUYEN),
    CONSTRAINT FK_VE_KH FOREIGN KEY(MAHK) REFERENCES BAITHI.KHACH(MAKH),
    CONSTRAINT PK_VX PRIMARY KEY(MATUYEN, MAHK)
);

SELECT
    *
FROM
    BAITHI.TUYEN;

--- 2. NHẬP DỮ LIỆU MẪU
INSERT INTO BAITHI.TUYEN VALUES(
    'T11A',
    'SG',
    'DL',
    210000,
    TO_DATE('26/12/2016', 'dd/MM/yyyy'),
    6
);

INSERT INTO BAITHI.TUYEN VALUES(
    'T32D',
    'PT',
    'SG',
    120000,
    TO_DATE('30/12/2016', 'dd/MM/yyyy'),
    4
);

INSERT INTO BAITHI.TUYEN VALUES(
    'T06F',
    'NT',
    'DNG',
    225000,
    TO_DATE('02/01/2017', 'dd/MM/yyyy'),
    7
);

INSERT INTO BAITHI.XE VALUES(
    'X01',
    '52LD-4393',
    'T11A',
    20,
    20
);

INSERT INTO BAITHI.XE VALUES(
    'X02',
    '59LD-7247',
    'T32D',
    36,
    36
);

INSERT INTO BAITHI.XE VALUES(
    'X03',
    '55LD-6850',
    'T06F',
    15,
    15
);

INSERT INTO BAITHI.KHACH VALUES(
    'KH01',
    'Lam Van Ben',
    'Nam',
    '655615896'
);

INSERT INTO BAITHI.KHACH VALUES(
    'KH02',
    'Duong Thi Luc',
    'Nu',
    '275648642'
);

INSERT INTO BAITHI.KHACH VALUES(
    'KH03',
    'Hoang Thanh Tung',
    'Nam',
    '456889143'
);

INSERT INTO BAITHI.VEXE VALUES(
    'T11A',
    'KH01',
    TO_DATE('20/12/2016', 'dd/MM/yyyy'),
    210000
);

INSERT INTO BAITHI.VEXE VALUES(
    'T32D',
    'KH02',
    TO_DATE('25/12/2016', 'dd/MM/yyyy'),
    144000
);

INSERT INTO BAITHI.VEXE VALUES(
    'T06F',
    'KH03',
    TO_DATE('30/12/2016', 'dd/MM/yyyy'),
    270000
);

--3. HIỆN THỰC RÀNG BUỘC TOÀN VẸN
ALTER TABLE BAITHI.TUYEN ADD CONSTRAINT CK_TUYEN CHECK((TGDK > 5
AND GIATUYEN > 200000) OR (TGDK <= 5));

--4. HIỆN THỰC RBTV

--5. TÌM TẤT CẢCÁC VÉ XE MUATRONG THÁNG 12, SẮP XẾP KẾT QUẢGIẢMDẦN THEO GIÁ VÉ
SELECT
    *
FROM
    BAITHI.VEXE
WHERE
    EXTRACT(MONTH FROM NGMUA) = 12
ORDER BY
    GIAVE DESC;

--6. TÌM TUYẾN XE CÓ SỐVÉ XEÍTNHẤTTRONG NĂM 2016.
SELECT
    T.MATUYEN,
    COUNT(*)
FROM
    BAITHI.TUYEN T,
    BAITHI.VEXE  V
WHERE
    T.MATUYEN = V.MATUYEN
    AND EXTRACT(YEAR FROM NGMUA) = 2016
GROUP BY
    T.MATUYEN
HAVING
    COUNT(*) <= ALL(
        SELECT
            COUNT(*)
        FROM
            BAITHI.TUYEN T,
            BAITHI.VEXE  V
        WHERE
            T.MATUYEN = V.MATUYEN
            AND EXTRACT(YEAR FROM NGMUA) = 2016
        GROUP BY
            T.MATUYEN
    );

--7. TÌM TUYẾN XECÓCẢHÀNH KHÁCH NAM VÀHÀNH KHÁCH NỮMUA VÉ
SELECT
    MATUYEN
FROM
    BAITHI.VEXE  V,
    BAITHI.KHACH K
WHERE
    K.MAKH = V.MAHK
    AND GIOITINH ='Nam' INTERSECT
    SELECT
        MATUYEN
    FROM
        BAITHI.VEXE  V,
        BAITHI.KHACH K
    WHERE
        K.MAKH = V.MAHK
        AND GIOITINH ='Nu';

--8. TÌM HÀNH KHÁCHNỮĐÃ TỪNG MUA VÉTẤT CẢCÁC TUYẾN XE
SELECT
    MAKH
FROM
    BAITHI.KHACH K
WHERE
    GIOITINH = 'Nu'
    AND NOT EXISTS(
        SELECT
            *
        FROM
            BAITHI.TUYEN T
        WHERE
            NOT EXISTS(
                SELECT
                    *
                FROM
                    BAITHI.VEXE  V
                WHERE
                    V.MATUYEN = T.MATUYEN
                    AND V.MAHK = K.MAKH
            )
    );