alter session set statistics_level = ALL;
-- Câu query đơn giản
SELECT DISTINCT HS.MAHS, TenHS, tinhtrang
FROM HAISAN HS, KHOHS_NVBH KB, HOADON HD, CTHD C, CUAHANG CH
WHERE CH.MACH = KB.MACH AND KB.MAHS = HS.MAHS AND HS.MAHS = 
C.MAHS AND C.MaHD = HD.MaHD 
AND CH.TenCH = 'Hai San Good' 
AND EXTRACT(YEAR FROM NgayLap) = 2023
 AND EXTRACT(MONTH FROM NgayLap) = 12
 AND TongTien > 500
AND SoLuong > 2;

-- EXPLAIN QUERY câu truy vấn đơn giản
SELECT /*+ GATHER_PLAN_STATISTICS */ DISTINCT HS.MAHS, TenHS, tinhtrang 
FROM ch2.HAISAN HS, ch2.KHOHS_NVBH KB, ch2.HOADON HD, ch2.CTHD C, ch1.CUAHANG CH WHERE CH.MACH = KB.MACH AND KB.MAHS = HS.MAHS AND HS.MAHS = C.MAHS AND C.MaHD = HD.MaHD 
	AND CH.TenCH = 'Hai San Best' 
	AND EXTRACT(YEAR FROM NgayLap) = 2023
    	AND EXTRACT(MONTH FROM NgayLap) = 12
    	AND TongTien > 500
 	AND SoLuong > 2;


-- code phân tích
SELECT * FROM TABLE(DBMS_XPLAN.display_cursor(format=>'ALLSTATS LAST'));

-- Viết lại câu query đã tối ưu trên môi trường phân tán
SELECT DISTINCT MAHS, TenHS, tinhtrang
FROM ((SELECT MACH, E.MAHS, TenHS, tinhtrang
 FROM ((SELECT C.MAHS, TenHS
 FROM ((SELECT MAHS
 FROM ((SELECT MaHD FROM CN1.HOADON
 WHERE EXTRACT(YEAR FROM NgayLap) = 2023 
 AND EXTRACT(MONTH FROM NgayLap) = 12
 AND TongTien > 500) A
 INNER JOIN (SELECT MaHD, MAHS
 FROM CN1.CTHD WHERE SoLuong > 2) B
 ON A.MaHD = B.MaHD)) C
 INNER JOIN (SELECT MAHS, TenHS
 FROM HAISAN) D ON C.MAHS = D.MAHS)) E
 INNER JOIN (SELECT MACH, MAHS, tinhtrang
 FROM CN1.KHOHS_NVBH) F ON E.MAHS = F.MAHS)) G
 INNER JOIN (SELECT MACH
 FROM CN1.CUAHANG WHERE TenCH = 'Hai San Good') H
 ON G.MACH = H.MACH);


SELECT /*+ GATHER_PLAN_STATISTICS */ DISTINCT MAHS, TenHS, tinhtrang
FROM ((SELECT MACH, E.MAHS, TenHS, tinhtrang
 FROM ((SELECT C.MAHS, TenHS
 FROM ((SELECT MAHS
 FROM ((SELECT MaHD FROM CN1.HOADON
 WHERE EXTRACT(YEAR FROM NgayLap) = 2023 
 AND EXTRACT(MONTH FROM NgayLap) = 12
 AND TongTien > 500) A
 INNER JOIN (SELECT MaHD, MAHS
 FROM CN1.CTHD WHERE SoLuong > 2) B
 ON A.MaHD = B.MaHD)) C
 INNER JOIN (SELECT MAHS, TenHS
 FROM HAISAN) D ON C.MAHS = D.MAHS)) E
 INNER JOIN (SELECT MACH, MAHS, tinhtrang
 FROM CN1.KHOHS_NVBH) F ON E.MAHS = F.MAHS)) G
 INNER JOIN (SELECT MACH
 FROM CN1.CUAHANG WHERE TenCH = 'Hai San Good') H
 ON G.MACH = H.MACH